{% raw %}
{% set data = load_setup_py_data(from_recipe_dir=True) %}

package:
  name: {{ data.get('name') }}
  version: {{ data.get('version') }}

source:
  path: ./

build:
  script: python setup.py install --single-version-externally-managed
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools

{% endraw %}