{% raw %}
{% set data = load_setup_py_data(from_recipe_dir=True) %}

package:
  name: {{ data.get('name') }}
  version: {{ data.get('version') }}

source:
  path: ./

requirements:
  build:
    - python
    - setuptools
    
  run:
    - python

{% endraw %}